const TICKETS_CONTRACT_ADDRESS = "0x4B87DA66CBBB18E24141731E1c3fdFbfA87F59b3";
const EVENTS_CONTRACT_ADDRESS = "0xdB09ddF4FFbAFc074184edae9CaD39a918FF5B5D";
const NET_RPC_URL = "https://api.avax-test.network/ext/bc/C/rpc";
const NET_RPC_URL_ID = "0xa869";
const TOKEN_NAME = "AVAX";
const NET_LABEL = "Avalanche Fuji Testnet";

module.exports = {
  TICKETS_CONTRACT_ADDRESS,
  EVENTS_CONTRACT_ADDRESS,
  NET_RPC_URL,
  NET_RPC_URL_ID,
  TOKEN_NAME,
  NET_LABEL,
};
